name: Build

on:
  push:
    branches:
      - "ci-test"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/pasteV.*.dmg
