name: Build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Rename
        run: mv dist/pasteV*.dmg dist/pasteV-${{ github.ref_name }}.dmg
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/pasteV*.dmg
